version: '3.3'

services:
  database:
      image: ubuntu/mysql:latest
      healthcheck:
          test: "exit 0"
      ports:
        - "3306:3306"
      env_file: .env
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      volumes:
          - ./db/dump:/docker-entrypoint-initdb.d
      networks:
          - app_net
  backend: 
    depends_on:
      - database
    ports: 
      - '8080:8080'
    env_file: .env
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
    build:
      context: ./backend
      target: builder
    networks:
      - app_net  

  frontend:
    depends_on:
      - frontend
    ports:
      - 5001:5001
    env_file: .env
    environment:
      VUE_APP_BACKEND_HOST: ${BACKEND_HOST}
      VUE_APP_BACKEND_PORT: ${BACKEND_PORT}
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/project
      - /project/node_modules
    networks:
      - app_net


networks:
    - app_net: []